title: GitHub Pages
description: >
  This site will get you started with GitHub Pages.
baseurl: "/pages-starter" # the subpath of your site
url: "https://Decoder76.github.io"
email: lovekesh677@hmail.com
github_username:  pm
linkedin_username: pm
twitter_username: pm